---
version: '2'
services:
  influxdb:
    image: influxdb 
    container_name: influxdb
    volumes:
      - "./influxdb/:/var/lib/influxdb"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="password"
      - INFLUXDB_DB="speedtest"

  grafana:
    image: pedrocesarti/internet-speedtest-docker:grafana 
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste

  speedtest:
    image: pedrocesarti/internet-speedtest-docker:speedtest
    container_name: speedtest
    links:
      - influxdb:db
    environment:
      - TEST_INTERVAL=5
